Task01 - Gilmanov RM
xthebat/iu4-2k23-python pull request #11
Opened 2023-02-25 22:21 UTC by RamzittoRamzotti

Сори, не туда пулреквестнул)

2023-02-26 23:55 UTC, shadowk1337 requested changes
Исправить

2023-02-26 23:55 UTC, shadowk1337 commented on Gilmanov_RM/task01/DZ1.py
> +    link = text[text.find("http"):len(text)]
А мы разве ссылки парсим? 🤔

2023-02-26 23:55 UTC, shadowk1337 commented on Gilmanov_RM/task01/DZ1.py
> +    file.close()
Лучше использовать
```python
with open() as f:
```

2023-02-26 23:55 UTC, shadowk1337 commented on Gilmanov_RM/task01/DZ1.py
> +        return False
```python
return len(link) <= number
```

2023-02-26 23:55 UTC, shadowk1337 commented on Gilmanov_RM/task01/DZ1.py
> +    return mass
Хммммммммммммммммммммммммммм, где-то я уже видел... Аааа, может [здесь](https://github.com/xthebat/iu4-2k23-python/pull/5/commits/f8c51190a9e17edfea112932ed707c87c5556bc5#:~:text=def%20lencheck(filename%3A%20str%2C%20lenght%3A%20int)%20%2D%3E%20bool%3A)
Вы там разберитесь, кто у кого что взял и исправьтесь плиз
Ну, а дальше потом посмотрю

2023-02-27 07:21 UTC, Sergeysers commented on Gilmanov_RM/task01/DZ1.py
> +    return mass
Моя вина, это я брал его код

2023-02-27 15:36 UTC, RamzittoRamzotti commented on Gilmanov_RM/task01/DZ1.py
> +    link = text[text.find("http"):len(text)]
Как раз таки не парсим, поэтому я рассчитываю на то, что ссылка будет самой длинной неделимой строкой, и подсчитываю исходя из этого количество минимальных символов для парса

2023-03-05 04:43 UTC, shadowk1337 approved these changes
Score: 4
- Base: +3
- Code Quality: +1

2023-03-08 09:20 UTC, xthebat commented on Gilmanov_RM/task01/DZ1.py
> +    return mass
-1 в Base, так делать не надо, я предупреждал

2023-03-08 09:21 UTC, merged

2023-03-08 10:02 UTC, RamzittoRamzotti commented on Gilmanov_RM/task01/DZ1.py
> +    return mass
Так не я же код брал, почему мне -?