Task01 - Zaharova A.
xthebat/iu4-2k23-python pull request #13
Opened 2023-02-26 20:24 UTC by Anastasya-art

2023-02-27 00:20 UTC, shadowk1337 requested changes
Надо поправить недочетики

2023-02-27 00:20 UTC, shadowk1337 commented on zaharova_ad/main.py
> +def open_file(file_split_data):
Давай назовем эту функцию по-другому, ведь она не только файл открывает

2023-02-27 00:20 UTC, shadowk1337 commented on zaharova_ad/main.py
> +        sys.exit(0)
Нуу, не думаю, что пользователь ожидает получить 0 в случае неуспешного завершения программы

2023-02-27 00:20 UTC, shadowk1337 commented on zaharova_ad/main.py
> +    with open(file=filename, mode='r', encoding='utf-8') as file:
`file=` и `mode=` лучше опустить и просто написать:
```python
with open(filename, 'r', encoding='utf-8') as file:
```

2023-02-27 00:20 UTC, shadowk1337 commented on zaharova_ad/main.py
> +        if '-l' in sys.argv:
Проверку аргументов программы тогда уж точно вынести в другую функцию

2023-02-27 00:20 UTC, shadowk1337 commented on zaharova_ad/main.py
> +def bonus_param_l(file_data):
Ээм советую тоже придать более смысловую окраску названию функции

2023-02-27 00:20 UTC, shadowk1337 commented on zaharova_ad/main.py
> +    for i in range(len(file_split_data)):
Лучше использовать `enumerate` и написать так
```python
for index, word in enumerate(file_split_data):
    if not word:
    ... 
```

2023-02-27 00:20 UTC, shadowk1337 commented on zaharova_ad/main.py
> +            file_split_data[nickname_index] += ' ' + file_split_data[i + 1]
Используй тут форматирование строк

2023-02-27 00:20 UTC, shadowk1337 commented on zaharova_ad/main.py
> +    for index in range(len(file_split_data)):
`enumerate`

2023-02-27 00:20 UTC, shadowk1337 commented on zaharova_ad/main.py
> +        sys.exit(0)
лучше вынести проверку отсюда в другое место, функция не отвечает за проверку аргументов программы

2023-02-27 00:20 UTC, shadowk1337 commented on zaharova_ad/main.py
> +        sys.exit(0)
Про возвращаемое значение написал выше

2023-02-27 00:20 UTC, shadowk1337 commented on zaharova_ad/main.py
> +    if not int(sys.argv[sys.argv.index('-n') + 1]):
а? Тут если не `int` выбросится исключение и смысла от проверки никакой

2023-02-27 00:20 UTC, shadowk1337 commented on zaharova_ad/main.py
> +    if not int(sys.argv[sys.argv.index('-n') + 1]):
И почему бы не воспользоваться переменной определенной выше `char_number`?

2023-02-27 00:20 UTC, shadowk1337 commented on zaharova_ad/main.py
> +            save_file(substring, i)
Эту проверку тоже лучше вынести

2023-02-27 00:20 UTC, shadowk1337 commented on zaharova_ad/main.py
> +        save_file(substring, i)
Эту тоже

2023-02-27 00:20 UTC, shadowk1337 commented on zaharova_ad/main.py
> +    sub_file.close()
А что тут мешало `with open() as` заюзать?))

2023-02-27 00:20 UTC, shadowk1337 commented on zaharova_ad/main.py
> +    print(result)
Бессмысленная функция, в топку

2023-02-27 00:20 UTC, shadowk1337 commented on zaharova_ad/main.py
> +        data = merge_words(data)
А зачем проверки аргументов разбросаны по всем местам программы, лучше собрать все проверки в одном месте и не возвращаться к ним больше

2023-02-27 06:15 UTC, Anastasya-art commented on zaharova_ad/main.py
> +    print(result)
А как тогда выводить строки в консоль?
В main запихнуть?

2023-02-27 08:14 UTC, shadowk1337 commented on zaharova_ad/main.py
> +    print(result)
Смотри, у тебя функция выполняет всего одну операцию `print`, какой смысл оборачивать `print` в еще одну функцию. Поменяй везде `print_line` на `print`

2023-02-27 14:19 UTC, Anastasya-art commented on zaharova_ad/main.py
> +    sub_file.close()
а есть принципиальная разница юзать метод либо мой либо через with open()?

2023-02-27 14:52 UTC, shadowk1337 commented on zaharova_ad/main.py
> +    sub_file.close()
Разница в том, что `with open as` сам следит за закрытием файла, а так ты должна следить сама за файлом и когда он закроется

2023-02-27 16:45 UTC, Anastasya-art commented on zaharova_ad/main.py
> +    if not int(sys.argv[sys.argv.index('-n') + 1]):
ну так у нас же вместе с -n  должно быть число,ничего другого быть не должно

2023-02-27 16:46 UTC, Anastasya-art commented on zaharova_ad/main.py
> +    if not int(sys.argv[sys.argv.index('-n') + 1]):
> И почему бы не воспользоваться переменной определенной выше `char_number`?

ты имеешь в виду просто задать char_number= 200?

2023-02-27 16:46 UTC, Anastasya-art commented on zaharova_ad/main.py
> +    sub_file.close()
Поняла,спасибо

2023-03-05 04:41 UTC, shadowk1337 approved these changes
Score: 6
- Base: +3
- Code Quality: +1
- Bonus 1: +1
- Bonus 2: +1

2023-03-08 09:18 UTC, xthebat commented on zaharova_ad/main.py
> +def bonus_param_l(file_data):
Смысл же получить доп. баллы, ты не понимаешь xD

2023-03-08 09:18 UTC, merged