Task01 Latypova_V
xthebat/iu4-2k23-python pull request #14
Opened 2023-02-26 22:03 UTC by latypovavictoria

Немного было непонятно по заданию Hardcore
 - Отписалась в комментариях

2023-03-05 03:17 UTC, shadowk1337 commented on Latypova_V_A/DZ/DZ.iml
> +</module>
Ненужные файлы надо удалить из репы

2023-03-05 03:17 UTC, shadowk1337 commented on Latypova_V_A/DZ/main.py
> +        return True
```python
return 0 == file_size_content
```

2023-03-05 03:17 UTC, shadowk1337 commented on Latypova_V_A/DZ/main.py
> +        status = False
А зачем создавать дополнительный уровень вложенности, ведь можно было просто написать так:
```python
if -1 == argv_f:
    print("Param -f is required")
    return -1
```
И после этого уже писать дальше всякие штуки без еще одного уровня вложенности

2023-03-05 03:17 UTC, shadowk1337 commented on Latypova_V_A/DZ/main.py
> +            status = False
```python
status = -1 != argv_l
```

2023-03-05 03:17 UTC, shadowk1337 commented on Latypova_V_A/DZ/main.py
> +            print_substrings(sys.argv[argv_f + 1], split_number, status)
По названию функции `print_substrings` вообще неочевидно, что она еще будет строки делить

2023-03-05 03:17 UTC, shadowk1337 commented on Latypova_V_A/DZ/main.py
> +            print_substrings(sys.argv[argv_f + 1], split_number, status)
Ну тут повторяющийся код - это плохо, проще можно было написать так:
```python
split_number = int(sys.argv[argv_n + 1]) if -1 != argv_n else 200
print_substrings(sys.argv[argv_f + 1], split_number, status)
```

2023-03-05 03:17 UTC, shadowk1337 commented on Latypova_V_A/DZ/main.py
> +        i += 1
Тут лучше было бы использовать `enumerate`

2023-03-05 03:17 UTC, shadowk1337 commented on Latypova_V_A/DZ/main.py
> +        file = open(file_name, 'r', encoding='utf-8')
Лучше использовать конструкцию `with open as` и тебе не придется руками следить за закрытием файла

2023-03-05 03:17 UTC, shadowk1337 commented on Latypova_V_A/DZ/main.py
> +        print("This file is not exist:(")
Тут `None` возвращается и нигде дальше по коду не чекается

2023-03-05 03:17 UTC, shadowk1337 commented on Latypova_V_A/DZ/main.py
> +            temp_file.close()
`with open as`

2023-03-05 03:17 UTC, shadowk1337 commented on Latypova_V_A/DZ/main.py
> +                            temp_list_string.append(read_string_new[current_index + 1:index_end_space + 1])
Давай по-честному - это вообще невозможно читать, попробуй упростить эту штуку, раздробить на функции

2023-03-05 03:17 UTC, shadowk1337 commented on Latypova_V_A/DZ/main.py
> +# i+=1
@xthebat

2023-03-05 03:18 UTC, shadowk1337 approved these changes
Score: 6
- Base: +3
- Code Quality: +1
- Bonus 1: +1
- Bonus 2: +1

2023-03-07 08:18 UTC, latypovavictoria commented on Latypova_V_A/DZ/main.py
> +        status = False
Это сделано для того, чтобы мы сначала проверяли введен ли `-f` параметр
Если нет, то зачем продолжать программу дальше
И здесь логика такая:
 - Если индекс  `argv_f` не равен -1 (ну т е во входных аргументах он присутствует), то идем дальше, а переменная `status` нужна для того, чтобы понимать введен ли параметр `-n`:
    - Если `-n` введен, то мы берем его значения из входящих аргументов и `status` равен `True`
    - Если же нет, то берем по умолчанию 200 и `status` равен `False`

2023-03-07 08:24 UTC, latypovavictoria commented on Latypova_V_A/DZ/main.py
> +            print_substrings(sys.argv[argv_f + 1], split_number, status)
Она не делит строки, туда просто передается параметр `split_number`, так как в дальнейшем этот параметр используется в функции `split_string`, и `split_string` вызывается как раз `print_substrings` 
А сделано это для того, чтобы избежать использования глобальных переменных
Можно, конечно, было инициализировать эту переменную внутри класса, но здесь я этим не воспользовалась

2023-03-08 09:12 UTC, xthebat commented on Latypova_V_A/DZ/main.py
> +        status = False
Магистр Йода присоединился к разработке кода... в питоне это не имеет смысла, потому что Вы не можете выполнить присвоение внутри условия `if argv_f = -1` - выдаст ошибку и PyCharm, и упадет во время выполнения. А уж тем более оператор != вообще не может даже в C/C++ быть использован как присвоение :) в условии. Для того, чтобы выполнить присвоение в условии в Python есть оператор `:=`. Поэтому такие извращения писать не надо.

2023-03-08 09:12 UTC, xthebat commented on Latypova_V_A/DZ/main.py
> +# i+=1
Лучше в ДС, у меня на почте 1000+ писем я даже не видел, что ты меня тегнул :|

2023-03-08 09:15 UTC, xthebat commented on Latypova_V_A/DZ/main.py
> +                            temp_list_string.append(read_string_new[current_index + 1:index_end_space + 1])
Тут должна быть картинка Микки-Мауса втыкающего руки себе в глаза :)
А если серьезно, хотя бы первое, что можно сделать это вынести `temp_list_string.append(` в конец этих if-else уже будет чуть проще. Разбить на функции, отследить логику if-else наверняка можно будет все в одну цепочку соединить if-elif

2023-03-08 09:17 UTC, xthebat requested changes
Либо я что-то не доглядел, либо надо поправить жуткую функцию или -1 за Code Quality, изменения можно вносить еще неделю.

2023-04-09 10:51 UTC, merged