Task01 Bazhenov KI
xthebat/iu4-2k23-python pull request #2
Opened 2023-02-22 18:39 UTC by kotyakostya1

+ Бонус 1 и Бонус 2

main - принимает входные параметры
sort_string - решает можно ли разделить строку и где это разделение будет
print_string - выводит разделенные строки в консоль (Бонус 2 - в разные файлы)

2023-02-23 11:11 UTC, shadowk1337 commented on Bazhenov_KI/main.py
> +
Общий совет: заглавными буквами в коде лучше обозначать константы, чтобы отличать их от переменных, а сами переменные лучше именовать в snake_case

2023-02-23 11:12 UTC, shadowk1337 commented on Bazhenov_KI/main.py
> +def sort_string(TEXT, MAX_INDEX, START_INDEX, INDEX_INC, L_RULE,D_RULE, FILE_CNT):
Давай подумаем над другим названием функции, ведь тут не только сортировка строки происходит

2023-02-23 11:14 UTC, shadowk1337 commented on Bazhenov_KI/main.py
> +        quit()
Так лучше работу программы не завершать, попробуй использовать возвращаемое значение функцией для обозначения успешности результата ее работы

2023-02-23 11:20 UTC, shadowk1337 commented on Bazhenov_KI/main.py
> +                CNT += 1
Можно объединить под один if

2023-02-23 11:22 UTC, shadowk1337 commented on Bazhenov_KI/main.py
> +                        quit()
Написал выше

2023-02-23 11:22 UTC, shadowk1337 commented on Bazhenov_KI/main.py
> +        quit()
Написал выше

2023-02-23 11:22 UTC, shadowk1337 commented on Bazhenov_KI/main.py
> +                quit()
Написал выше

2023-02-23 11:23 UTC, shadowk1337 commented on Bazhenov_KI/main.py
> +                        CNT = CNT_SAVE + 1
Слишком много вложенных условий в цикле : ( Нельзя ли как-то упростить?

2023-02-23 11:24 UTC, shadowk1337 commented on Bazhenov_KI/main.py
> +        # os.mknod("str" + FILE_CNT + " .txt")
Такие закомментированные строки лучше удалять

2023-02-23 11:38 UTC, shadowk1337 commented on Bazhenov_KI/main.py
> +         # Нужно вернуться к началу выполнения функции
Нужно :) А лучше просто завершить выполнение программы

2023-02-23 11:38 UTC, shadowk1337 commented on Bazhenov_KI/main.py
> +    print('Введите -f "путь к файлу" -n "Максимальное количество символов"')
То есть сразу после обращения к программе будет выводиться сообщение с его флагами? А зачем

2023-02-23 11:39 UTC, shadowk1337 commented on Bazhenov_KI/main.py
> +        quit()
Можно просто использовать return

2023-02-23 11:39 UTC, shadowk1337 commented on Bazhenov_KI/main.py
> +        quit()
Можно просто использовать return

2023-02-23 11:41 UTC, shadowk1337 commented on Bazhenov_KI/main.py
> +    file = open(sys.argv[2])
Тут можно обернуть открытие файла, так же как ты сделал в функции выше с помощью `with open() as`

2023-02-23 11:43 UTC, shadowk1337 reviewed
Если есть время, то лучше исправь недочеты и в принципе будет нормас
Чтобы залить изменения просто закомить их у себя в репозитории, в pull request они сами подтянутся

2023-02-26 09:27 UTC, xthebat requested changes
Нет разделения логики обработки и логики вывода на экран/файл. 
Это надо фиксить :(

2023-02-26 09:27 UTC, xthebat commented on Bazhenov_KI/main.py
> +    if (processing_and_cropping_str(text, max_index, start_index, INDEX_INC, l_rule, d_rule, file_cnt) == 0):
Скобки вокруг условия if - не нужны. См. все подсказки IntelliJ/Python - IDE подсвечивает, если ваш код можно упростить или в нем есть потенциальная ошибка.

2023-02-26 09:27 UTC, xthebat commented on Bazhenov_KI/main.py
> +    if (processing_and_cropping_str(text, max_index, start_index, INDEX_INC, l_rule, d_rule, file_cnt) == 0):
Обычно в Python не используется возврат числа в качестве статуса. Для этого есть исключения (мы их пока не проходили), либо возвращается необходимое значение или `None`.

2023-02-26 09:27 UTC, xthebat commented on Bazhenov_KI/main.py
> +def print_string(end_index, max_index, text, start_index, INDEX_INC, l_rule, d_rule, file_cnt) -> int:
Логика вывода обработанной информации не отделена от логики обработки информации. Из-за этого у Вас огромное количество аргументов у функций. Точнее это сделано больше формально, но не структурно. То есть Вы должны были в начале обработать входную строку, на выходе получить список строк. После этого, следующей функцией уже выводить полученный список строк в стандартный поток вывода.

То что сейчас получилось - да функция вывода в поток или файл - есть. Но она вызывается внутри функции обработки. Результат - весь код одно перемешан как клубок ниток.

2023-02-26 09:27 UTC, xthebat commented on Bazhenov_KI/main.py
> +        with open (sys.argv[7] + "str" + str(file_cnt) + ".txt", "w") as new_file:
Клеить строки - это плохо: не читаемо. Используйте интерполяцию строк. Я показывал это на стриме: `f"{file_cnt}_XXX.txt"`

2023-02-26 09:27 UTC, xthebat commented on Bazhenov_KI/main.py
> +        with open (sys.argv[7] + "str" + str(file_cnt) + ".txt", "w") as new_file:
Аргументы, также необходимо парсить отдельно. Сейчас у Вас не разобранные аргументы передаются в самую глубину логики программы. Это очень плохой код. Не Вы (через пару недель), не я, не кто-либо еще не сможет сказать, что находится в `sys.argv[7]`.

2023-02-26 09:27 UTC, xthebat commented on Bazhenov_KI/main.py
> +        with open (sys.argv[7] + "str" + str(file_cnt) + ".txt", "w") as new_file:
После `open` скобка не ставится. Такое форматирование кода - это примерно также как расстановка пробелов перед запятыми. Используйте автоформат кода.

2023-02-26 09:27 UTC, xthebat commented on Bazhenov_KI/main.py
> +    else:
else не нужен, выполнение завершиться, если условие в if выполнилось.

2023-02-26 09:27 UTC, xthebat commented on Bazhenov_KI/main.py
> +    if param_name == '-f':
Лучше идти по пути как было в 66-й строки при парсе аргументов. Если аргументы заданы не корректно - просто выходим из функции с сообщением. Кода будет меньше и его проще читать и понимать.

2023-02-26 09:27 UTC, xthebat commented on Bazhenov_KI/main.py
> +    if param_name == '-n':
С точки зрения разбора аргументов дополнительных условий кроме ключи не было. Поэтому предполагать, что аргументы будут всегда на одинаковых местах - некорректно. Необходимо использовать либо метод find/index у списка, либо в цикле находить нужный аргумент (первый вариант - лучше).

2023-02-26 09:27 UTC, xthebat commented on Bazhenov_KI/main.py
> +        FILE_PATH = sys.argv[2]
Все локальные переменные пишутся в snake_case (маленькие буквы через подчерк) - это стандартизировано в PEP8.

2023-02-26 09:27 UTC, xthebat commented on Bazhenov_KI/main.py
> +        max_index = int(sys.argv[4]) + 1
Не очень удачный нейминг (именование). index - это обычно положение в строке/списке. Данные аргумент указывает на количество, что обычно именуется как: count, size, number. Это важно, так как, чем проще из названия понять, что представляет собой переменная, тем проще читать и анализировать Ваш код.

2023-02-26 09:27 UTC, xthebat commented on Bazhenov_KI/main.py
> +    with open (sys.argv[2], "r") as file:
Где-то выше писал, что аргументы лучше разложить по переменным после их (аргументов) разбора.

2023-02-26 09:27 UTC, xthebat commented on Bazhenov_KI/main.py
> +    if (processing_and_cropping_str(text, max_index, start_index, INDEX_INC, l_rule, d_rule, file_cnt) == 0):
Функция должна возвращать список строк после разбивки входной строки или None, если что-то пошло не так.

2023-02-26 09:27 UTC, xthebat commented on Bazhenov_KI/main.py
> +            new_file.write("%s" % final_str)
Используйте интерполяцию строк. У Вас в программе из 100 строк два способа сбора строки: склейка и форматирование. Зачем? Это только усложняет чтение. Более того, здесь вообще не нужно не форматирование, не склейка. Можно писать строку напрямую в файл.

2023-02-26 09:27 UTC, xthebat commented on Bazhenov_KI/main.py
> +    if processing_and_cropping_str(text, max_index, start_index, INDEX_INC, l_rule, d_rule, file_cnt) == 0:
Ну рекурсия тут вообще финиш :( Оверинжиниринг

2023-02-26 09:27 UTC, xthebat commented on Bazhenov_KI/main.py
> +                if (l_rule == 1):
Скобки не нужны

2023-02-26 09:27 UTC, xthebat commented on Bazhenov_KI/main.py
> +            new_file.write("%s" % final_str)
Писать в файл можно еще и обычным print: `print(string1, string2, file=new_file)`

2023-02-27 08:45 UTC, kotyakostya1 reviewed
Прошлый коммит не с последней версией программы, перепутал.

2023-03-05 04:29 UTC, shadowk1337 approved these changes
Score: 5
- Base: +3
- Bonus 1: +1
- Bonus 2: +1

2023-03-09 18:16 UTC, merged