Task 01 - Shirinov P.
xthebat/iu4-2k23-python pull request #21
Opened 2023-02-28 13:06 UTC by PlatonShirinov

2023-03-05 00:49 UTC, shadowk1337 requested changes
Надо доделать задание - сделать запрет разделения строка по **тегам**, **датам**, **ссылкам** и тд

Также надо исправить недочеты

2023-03-05 00:49 UTC, shadowk1337 commented on task11.py
> +
Коменты для каждой строки - моветон. И так понятно, что происходит в каждой строке, а коменты просто сбивают с толку, так делать не стоит - пиши код, чтобы он был понятен без коментов

2023-03-05 00:49 UTC, shadowk1337 commented on task11.py
> +def split_string(input_string, max_length):
Типы для аргументов функции и тип возвращаемого значения

2023-03-05 00:49 UTC, shadowk1337 commented on task11.py
> +def print_substrings(substrings):
Тип для аргумента

2023-03-05 00:49 UTC, shadowk1337 commented on task11.py
> +        substrings.append(input_string[start_index:end_index])#.strip())
Лишний закоменченый код тоже стоит удалять, от него толку никакого - к нему ты больше вряд ли вернешься

2023-03-05 00:49 UTC, shadowk1337 commented on task11.py
> +            last_space = input_string.rfind(" ", start_index, end_index)
А ты точно уверено, что в твоей строке будет пробел?

2023-03-05 00:49 UTC, shadowk1337 commented on task11.py
> +            if near_space - end_index <= end_index - last_space:
`near_space` - индекс пробела справа от `end_index`, `last_space` - слева, условие выполнится, если `near_space` == `last_space` == `end_index`. Притом если в качестве `end_index` оставлять `near_space`, то у тебя получается нарушение условия задачи - длина строки получится больше заданной

2023-03-08 06:54 UTC, shadowk1337 approved these changes
Score: 4
- Base: +3
- Code Quality: +1

2023-03-08 08:45 UTC, xthebat commented on task11.py
> +        substrings.append(input_string[start_index:end_index])#.strip())
Тут еще нарушение PEP8: комментарий к концу строки ставит после двух пробелов

2023-03-08 08:46 UTC, xthebat commented on task11.py
> +            last_space = input_string.rfind(" ", start_index, end_index)
Такие комментарие практически бессмыслены - достаточно знать, что делает rfind, и все что написано в комментарии становится понятным

2023-03-08 08:47 UTC, xthebat commented on Shirinov_PP/task1_finish.py
> +    else:
else не нужен, загромождает код и возникает ощущение, что есть возврат из 73 строки - но его нету.

2023-03-08 08:48 UTC, xthebat commented on Shirinov_PP/task1_finish.py
> +def split_string(input_string : str, max_length : int) -> list:
Нарушение PEP8 - используйте автоформатирование из PyCharm

2023-03-08 08:49 UTC, xthebat commented on Shirinov_PP/task1_finish.py
> +        if symb == ' ' and point:
Очень странная конструкция if-elif, а потом на ту же переменную снова if - возникает ощущение, что тут что-то не так

2023-03-08 08:56 UTC, xthebat commented on Shirinov_PP/task1_finish.py
> +    changed_string = ""
Склейка строк в цикле - это очень плохо и выдает не знание Python, так и других языков. Во многих языках (Python, Java/JVM, C#, C++) строка - это неизменяемый тип данных. Поэтому при доклеивание к строке через в цикле Вы вызывает перекопирование всей строки каждый раз. Правильней использовать StringBuilder (JVM, C#) или список, а потом собрать итоговую строку.

2023-03-08 08:56 UTC, xthebat commented on Shirinov_PP/task1_finish.py
> +    lst = str_input.split()
`wmax = max(len(it) for it in str_input.split())`

2023-03-08 08:56 UTC, xthebat commented on Shirinov_PP/task1_finish.py
> +            print(f"Маленькое значение для разбиения")
Help на английском, а ошибки на русском :)

2023-03-08 08:56 UTC, xthebat commented on Shirinov_PP/task1_finish.py
> +def print_substrings(substrings:str):
Опять PEP8 был заигнорен, причем каждый раз, разный код-стайл.
Такое чувство, что код писали разные люди. С случае, если код пишут несколько программистов и можно определить, какую часть кто написал по код-стайлу - это уже "дурной знак". А если один программист так делает - это ещё хуже. Ваш код должен соответствовать принятым в команде стандартам разработки - у нас это PEP8 (да и в большинстве случае в базе лежит этот стандарт для Python)

2023-03-08 08:57 UTC, merged