Task01 - Krawez Gleb
xthebat/iu4-2k23-python pull request #26
Opened 2023-02-28 19:30 UTC by KrawezG

2023-03-02 15:34 UTC, shadowk1337 requested changes
Пересмотри свой код, в качестве опоры можешь посмотреть примеры других

2023-03-02 15:34 UTC, shadowk1337 commented on main.py
> +        print_strings(substrings)
Емае, это вообще не pythonic-way написание. Тут даже не в питоне дело, никто не проверяет руками через индексы наличие аргумента... В питоне же есть функции `find`, `index` и тд, операция `in`. Зачем такое городить? Это же вообще капец, ты в сумме проверил наличие аргумента `-f` 9 раз, это вообще не ок, так лучше не писать

2023-03-02 15:34 UTC, shadowk1337 commented on main.py
> +    file = open(filepath, encoding='utf-8')
В питоне для того, чтобы самому не следить за закрытием файла есть конструкция `with open as`

2023-03-02 15:34 UTC, shadowk1337 commented on main.py
> +    #print(f"Word length {len(sorted_list[-1])=}")
Такие комментарии в коде не нужны - лучше их убирать

2023-03-02 15:34 UTC, shadowk1337 commented on main.py
> +        return False
```python
return len(sorted_list[-1]) < length
```

2023-03-02 15:34 UTC, shadowk1337 commented on main.py
> +    list_ = list(text.split(" "))
`text.split(" ")` и так возвращает список, зачем его еще раз к списку кастить

2023-03-02 15:34 UTC, shadowk1337 commented on main.py
> +    for i in range(len(strings)):
`range(len())` можно заменить на `enumerate`

2023-03-02 15:34 UTC, shadowk1337 commented on main.py
> +    file.close()
Зачем тут опять файл открывать и считывать с него что-то

2023-03-02 15:34 UTC, shadowk1337 commented on main.py
> +    flag = 0
Переменные лучше определять ближе к их использованию, чтобы они не занимали лишнюю область видимости

2023-03-02 15:34 UTC, shadowk1337 commented on main.py
> +                if i[0] == "@":
`startswith`

2023-03-07 15:51 UTC, shadowk1337 approved these changes
Score: 3
- Base: +3

2023-03-08 08:32 UTC, xthebat commented
Надо поправить расположение файлов

2023-03-08 08:58 UTC, xthebat requested changes
Необходимо перенести файлы

2023-03-10 17:13 UTC, KrawezG commented
Это мне надо создать новую ветку с правильным названием и замерджить ее с этой?

2023-03-10 17:52 UTC, shadowk1337 commented
> Это мне надо создать новую ветку с правильным названием и замерджить ее с этой?

Merge'ишь ветки не ты. Тебе надо кинуть свой pr не в ветку master, а в ветку task01, также надо поправить расположение файлов, а именно сделать, чтобы main.py лежал в директории с твоими фамилией_ио

2023-03-10 19:34 UTC, KrawezG commented
Вроде сделал новый пулл, теперь правильно?

2023-03-11 13:33 UTC, closed without merging