Task 01 Radchuk A. P.
xthebat/iu4-2k23-python pull request #3
Opened 2023-02-23 16:23 UTC by Anastasiia29-11

Задание hardcore сделано по Вашему примеру из дискорда (удаление строк по булевой функции).

2023-02-23 21:56 UTC, shadowk1337 commented on radchuk_ap/task01/dz1.py
> +
Не совсем понял почему названия некоторых функций написаны заглавными буквами, а есть, к примеру, `save_append`, название которой написано не заглавными буквами. Такой же вопрос и к наименованию аргументов и переменных. Вообще заглавными буквами в питоне принято обозначать только константы

2023-02-23 21:57 UTC, shadowk1337 commented on radchuk_ap/task01/dz1.py
> +def ERROR(msg, code):
А как тут тогда используется аргумент `code`?))

2023-02-23 21:58 UTC, shadowk1337 commented on radchuk_ap/task01/dz1.py
> +	exit(0)
Возвращение нуля подразумевает успешное завершение программы. Думаю, не стоит при ошибках возвращать здесь ноль

2023-02-23 22:01 UTC, shadowk1337 commented on radchuk_ap/task01/dz1.py
> +	param5 = "lambda r: True"
Ок, а если бы параметров было бы не 5 штук, а больше, тогда бы пришлось для каждого параметра создавать переменную paramN. Может быть стоит назвать их посущественнее или обратиться к каким-нибудь коллекциям

2023-02-23 22:03 UTC, shadowk1337 commented on radchuk_ap/task01/dz1.py
> +				pass
Думаю, проверка остальных случаев в `match` не заслуживает 2 строк кода))

2023-02-23 22:05 UTC, shadowk1337 commented on radchuk_ap/task01/dz1.py
> +	if param4 != None and not os.path.exists(param4):
В принципе, проверку можно было бы написать вот так: `if param4 != None and not os.path.exists(param4):`

2023-02-23 22:06 UTC, shadowk1337 commented on radchuk_ap/task01/dz1.py
> +		if len(substring) != 0:
Можно так `if len(substring):`

2023-02-23 22:07 UTC, shadowk1337 commented on radchuk_ap/task01/dz1.py
> +	if is_d_param != None:
Можно так `if is_d_param:`

2023-02-23 22:10 UTC, shadowk1337 commented on radchuk_ap/task01/dz1.py
> +			print(lst[i])
Можно так
```python
for idx, word in enumerate(lst):
	print(f"Substring #{idx}:")
	print(word)
```

2023-02-23 22:12 UTC, shadowk1337 commented on radchuk_ap/task01/dz1.py
> +			for j in range(len(new_list_of_words)):
Как упростить запись цикла, написал ниже по коду, здесь достаточно использовать `enumerate`

2023-02-23 22:16 UTC, shadowk1337 reviewed
В принципе нормас, надо бы исправить некоторые неточности и, наверное, первое дз сдашь :)

2023-02-26 09:48 UTC, xthebat requested changes
Score: 
- Base: -
- Code Quality: -
- Bonus 1: +1
- Bonus 2: +1
- Hardcore: +2

Задание выполнено, но необходимо исправить форматирование (имена функций и переменных).

2023-02-26 09:48 UTC, xthebat commented on radchuk_ap/task01/dz1.py
> +				param1 = sys.argv[i + 1]
Было бы хорошо проверить, что следующий индекс, есть в списке. Но то, что уже есть разбор аргументов: +

2023-02-26 09:48 UTC, xthebat commented on radchuk_ap/task01/dz1.py
> +	for i in range(len(sys.argv)):
~~Разбор аргументов можно вынести в функцию, но для этого либо надо возвращать кучу переменных через tuple, либо использовать dataclass (что я не показывал). Оставляем так :)~~
Из-за кучи комментариев в PR не заметил, что это отдельная функция :)

2023-02-26 09:48 UTC, xthebat commented on radchuk_ap/task01/dz1.py
> +	if param4 != None and not os.path.exists(param4):
Проверять на None через !=/= некорректно (это замедлит код). Да, я забыл про это сказать. Правильно использовать оператор `is`: `param4 is not None`, либо как указано выше.

2023-02-26 09:48 UTC, xthebat commented on radchuk_ap/task01/dz1.py
> +				param3 = True
Грустно, что так назвали аргументы. Почему не дать им хорошие имена. Неужели Вы и котиков называли бы kot1, kot2, kot3, kot4. А если серьёзно, то через пару недель для Вас этот код будет выглядеть, как будто его писал другой человек и будет очень сложно вспомнить, что же такое param3, param2 и т.п. 

Именуйте переменные так, чтобы не нужно было тратить время на разбирания что в них хранится/для чего эти переменные.

2023-02-26 09:48 UTC, xthebat commented on radchuk_ap/task01/dz1.py
> +def PARSE(FILE_PATH, MAX_SYMBOLS, IS_L_PARAM, IS_R_PARAM):
Функции, аргументы пишутся в snake_case

2023-02-26 09:48 UTC, xthebat commented on radchuk_ap/task01/dz1.py
> +	FILE_PATH, MAX_SYMBOLS, IS_L_PARAM, IS_D_PARAM, IS_R_PARAM = CHECK_INPUT()
Это , отформатировано, ужасно ...  

Неужели IntelliJ/PyCharm не указала не одного предупреждения.

2023-02-26 09:48 UTC, xthebat commented on radchuk_ap/task01/dz1.py
> +def CHECK_INPUT():
snake_case

2023-02-26 09:48 UTC, xthebat commented on radchuk_ap/task01/dz1.py
> +			if IS_L_PARAM and i[0] == '-':
Фактически стандартом в написании кода является, что всё что названо `is_.....` - это bool (логическая переменная). Поэтому некорректно именовать строковые и другие переменные, кроме был с префиксом `is_`. Это сбивает с толку и усложняет чтение кода.

2023-02-26 09:48 UTC, xthebat commented on radchuk_ap/task01/dz1.py
> +	l_f = eval(IS_R_PARAM)
См. комментарий к 59-й строке.

2023-02-26 09:48 UTC, xthebat commented on radchuk_ap/task01/dz1.py
> +		substring = ""
Клеить строки (накапливать строки) в Python и 90% других языков - плохая идея. Строки обычно не изменяемый тип данных. Это значит, что на каждое += будет перевыделяться память на всю строку и будет происходить копирование всей строки. Это замедлит Ваш код и частенько, даже очень сильно. Лучше создать тут список или bytearray (но его не проходили), а потом преобразовать в строку, когда соберете все кусочки.

2023-02-26 09:48 UTC, xthebat commented on radchuk_ap/task01/dz1.py
> +def PARSE(FILE_PATH, MAX_SYMBOLS, IS_L_PARAM, IS_R_PARAM):
В целом код лучше, чем предыдущий, который я смотрел, но: у функции тело имеет очень большую вложенность по табуляциям. Лучше разбить ее на ряд функций по логике того, что там происходить. Это улучшит читабельность кода.

2023-03-08 06:56 UTC, shadowk1337 approved these changes
Score: 8
- Base: +3
- Code Quality: +1
- Bonus 1: +1
- Bonus 2: +1
- Hardcore: +2

2023-03-08 12:06 UTC, merged