Task01 - Khokhlunova O.
xthebat/iu4-2k23-python pull request #30
Opened 2023-02-28 20:38 UTC by Snezhok1999

2023-03-02 13:03 UTC, shadowk1337 requested changes
Программа на тесткейсе
`python main.py -f "file.txt" -n 20`
улетает в бесконечный цикл, надо фиксить
```
<file.txt>
fads fdsa fsda fasdfiqjewflbs akldfh psodihfpog hdsalfkjlqwjdfoighqew 
adsfsd 
fsd 
afdas 
fd 
sfq e 
qwrewq fewqfewqf  
sdf @Amogus Amogus:1338 
```

2023-03-02 13:03 UTC, shadowk1337 commented on main.py
> +def add_parser_args(parser):
Типы в аргументах функции

2023-03-02 13:03 UTC, shadowk1337 commented on main.py
> +def process_file(input, max_num):
Типы в аргументах функции и в возвращающем значении

2023-03-02 13:03 UTC, shadowk1337 commented on main.py
> +def print_s(substrings):
Типы в аргументах функции

2023-03-02 13:03 UTC, shadowk1337 commented on main.py
> +def write_s(substrings, dirpath):
Типы в аргументах функции

2023-03-02 13:03 UTC, shadowk1337 commented on main.py
> +def print_s(substrings):
Лучше не называть функции такими сокращенными названиями, так как пользователь твоей функции по имени не сможет догадаться, что она делает. `print_s` - это `print_secured` или `print_stop`? Непонятно

2023-03-02 13:03 UTC, shadowk1337 commented on main.py
> +def write_s(substrings, dirpath):
По названию функции написал выше

2023-03-02 13:03 UTC, shadowk1337 commented on main.py
> +    for s in substrings:
Такой цикл писать не pythonic-way - это сиподобный цикл. В питоне есть функция `enumerate`, которая делает то же самое только вболее удобочитаемом виде

2023-03-02 13:03 UTC, shadowk1337 commented on main.py
> +    for s in substrings:
Про такой цикл написал выше по коду

2023-03-02 13:03 UTC, shadowk1337 commented on main.py
> +        with open(os.path.join(dirpath, f'substring_{i}.txt'), 'wt') as fout:
Ммм, а зачем городить такие длинные конструкции? Проще вынести результат работы функции `os.path.join` в отдельную переменную и сюда передавать эту переменную. И в последстии при отладке это может помочь, так как на строку с названием файла можно будет поставить брейкпоинт

2023-03-02 13:03 UTC, shadowk1337 commented on main.py
> +        return
Тут и дальше лучше возвращать результат работы мейна в виде кода состояния тогда уж, так как кто-то может пользоваться твоей программой. Проще для вида тут `-1` возвращать

2023-03-02 13:03 UTC, shadowk1337 commented on main.py
> +    while i < len(input):
Можно заменить на `enumerate` и отказаться от использования `i`

2023-03-02 13:03 UTC, shadowk1337 commented on main.py
> +            result.append(input[i : i + max_num])
Тут в слайсе пробелы не нужны около двоеточия

2023-03-06 08:28 UTC, shadowk1337 approved these changes
Score: 5
- Base: +3
- Code Quality: +1

- Bonus 2: +1

2023-03-08 08:30 UTC, xthebat commented
Надо поправить расположения файла, я не могу замерджить PR и задание будет считаться не принятым. Кто-то ещё также положил в корень task01 файл main.py - но он был первым :)

2023-03-08 08:57 UTC, xthebat requested changes
Необходимо перенести файлы

2023-03-08 09:55 UTC, merged