task01-Islomboev
xthebat/iu4-2k23-python pull request #34
Opened 2023-02-28 20:57 UTC by IslomboevBotir

На данном этапе программа разбивает строку на подстроки с требованиям на то ,что по середины слова не разделяются.

2023-03-01 14:38 UTC, shadowk1337 requested changes
Нужно доделать нормально основную часть программы

2023-03-01 14:38 UTC, shadowk1337 commented on task01/task1.py
> +
Нет разделения на обработку строки и вывод строки

2023-03-01 14:38 UTC, shadowk1337 commented on task01/task1.py
> +def smash(text_word, n):
Добавь типы к аргументам функции

2023-03-01 14:38 UTC, shadowk1337 commented on task01/task1.py
> +    while True:
Ммм, не очень классный цикл без условия

2023-03-01 14:38 UTC, shadowk1337 commented on task01/task1.py
> +        exit(0)
При ошибке обычно в качестве кода возвращают не ноль

2023-03-01 14:38 UTC, shadowk1337 commented on task01/task1.py
> +def smash(text_word, n):
Также имя функции не описывает того, что в ней происходит. Также имена аргументов выбраны не очень, ты в мейне передаешь сюда `text_data` и `n`, что такое `n` из названия функции не очень понятно. Также 'text_word`, в нем же не одно слово содержится

2023-03-01 14:38 UTC, shadowk1337 commented on task01/task1.py
> +        return result
А какой смысл этой проверки, если дальше в цикле ты проверяешь то же самое?

2023-03-01 14:38 UTC, shadowk1337 commented on task01/task1.py
> +        exit(0)
Написал выше

2023-03-01 14:38 UTC, shadowk1337 commented on task01/task1.py
> +    k = 1
Зачем тут `k`, лучше цикл ниже с помощью `enumerate` перепиши

2023-03-01 14:38 UTC, shadowk1337 commented on task01/task1.py
> +        k += 1
Вынеси все это в отдельную функцию

2023-03-01 14:38 UTC, shadowk1337 commented on task01/task1.py
> +                text_word[right] != ' ' and text_word[right] != '\t' and text_word[right] != '\n':
Тут эту длинную проверку можно заменить на [isspace](https://www.w3schools.com/python/ref_string_isspace.asp)

2023-03-01 14:38 UTC, shadowk1337 commented on task01/task1.py
> +                if text_part[i] == ' ' or text_part[i] == '\t' or text_part[i] == '\n':
[isspace](https://www.w3schools.com/python/ref_string_isspace.asp)

2023-03-01 14:38 UTC, shadowk1337 commented on task01/task1.py
> +                if text_word[i] == ' ' or text_word[i] == '\t' or text_word[i] == '\n':
[isspace](https://www.w3schools.com/python/ref_string_isspace.asp)

2023-03-01 14:38 UTC, shadowk1337 commented on task01/task1.py
> +            for i in reversed(range(len(text_part))):
Для упрощение можно использовать `enumerate`

2023-03-01 14:38 UTC, shadowk1337 commented on task01/task1.py
> +                    break
В питоне есть функция [rfind](https://www.w3schools.com/python/ref_string_rfind.asp), которая ищет символ с конца

2023-03-01 14:38 UTC, shadowk1337 commented on task01/task1.py
> +    while True:
Цикл не из мира питона, в питоне же есть функции, упрощающие работу со строками, зачем искать символы с помощью еще одних циклов...

2023-03-01 14:38 UTC, shadowk1337 commented on task01/task1.py
> +            for i in range(start_word_index, len(text_word)):
В питоне же есть функция `find`...

2023-03-19 18:09 UTC, IslomboevBotir commented
Задание сделано, проверьте пожалуйста

2023-03-29 12:49 UTC, shadowk1337 approved these changes
Score: 4
- Base: +3
- Bonus 1: +1

2023-04-09 10:56 UTC, merged