Task01 - Khamidullin A.
xthebat/iu4-2k23-python pull request #36
Opened 2023-02-28 21:09 UTC by beplop

2023-03-01 06:48 UTC, shadowk1337 requested changes
Надо поправить недочеты

2023-03-01 06:48 UTC, shadowk1337 commented on khamidullin_ar/input.txt
> +Scoreboard ���� ������: https://discord.com/channels/690164243685048457/806462228207239179/941307720076783686
А что с кодировкой

2023-03-01 06:48 UTC, shadowk1337 commented on khamidullin_ar/main.py
> +    tokens = text_to_tokens(words)
Функция ожидает строку - получает список строк

2023-03-01 06:48 UTC, shadowk1337 commented on khamidullin_ar/main.py
> +def file_handler(args: list[str]) -> bool or dict:
Функция обрабатывает аргументы программы, а называется  `file_handler`, лучше переназови ее по-другому

2023-03-01 06:48 UTC, shadowk1337 commented on khamidullin_ar/main.py
> +        if re.match('(\w:.+)|(.+\.\w+)', args[f_pos + 1]):
От `regexp` лучше здесь отказаться, далеко неочевидно, что он тут делает и это очень мешает при чтении твоего кода, так как приходится обращаться к документации `regexp`

2023-03-01 06:48 UTC, shadowk1337 commented on khamidullin_ar/main.py
> +            f_name = args[f_pos + 1]
В принципе, переменную `f_name` можно было создать раньше, сразу после 9 строки

2023-03-01 06:48 UTC, shadowk1337 commented on khamidullin_ar/main.py
> +            n_value = args[n_pos + 1]
Написал про создание переменной выше

2023-03-01 06:48 UTC, shadowk1337 commented on khamidullin_ar/main.py
> +def text_to_tokens(words: str) -> list[str]:
Название функции обычно должно начинаться с глагола

2023-03-01 06:48 UTC, shadowk1337 commented on khamidullin_ar/main.py
> +def text_to_tokens(words: str) -> list[str]:
А ты точно ожидаешь, что функция должна принимать строку? Потому что по коду дальше, кажется, что ты ожидаешь список здесь

2023-03-01 06:48 UTC, shadowk1337 commented on khamidullin_ar/main.py
> +            if words[i].endswith(':') or words[i].endswith(':/n'):
`words[i].endswith(':/n')` можно поменять на `words[i].endswith('/n')`

2023-03-01 06:48 UTC, shadowk1337 commented on khamidullin_ar/main.py
> +            tokens.append(words[i])
Вместо того, чтобы каждый раз обращаться к `words[i]`, можно вынести в переменную

2023-03-01 06:48 UTC, shadowk1337 commented on khamidullin_ar/main.py
> +def tokens_to_substrings(tokens: list[str], n: int) -> list[str] or bool:
Про название функции написал выше

2023-03-01 06:48 UTC, shadowk1337 commented on khamidullin_ar/main.py
> +        if re.match('\d+', args[n_pos + 1]):
Ну тут более менее

2023-03-01 06:48 UTC, shadowk1337 commented on khamidullin_ar/main.py
> +    if sub_strings:
Бесполезная проверка

2023-03-01 06:48 UTC, shadowk1337 commented on khamidullin_ar/main.py
> +        if sum([len(x) for x in buffer]) + len(token) + len(buffer) - 1 <= n:
А зачем тут `len(buffer)` учитывать?

2023-03-05 17:18 UTC, beplop commented on khamidullin_ar/main.py
> +        if re.match('(\w:.+)|(.+\.\w+)', args[f_pos + 1]):
Я тут просто проверяю, что после аргумента -f действительно записан путь файла (например C:\Files\input.txt) или имя файла (например input.txt). Напишу комментарий в коде, чтобы понятнее было, но удалять не хочу

2023-03-05 17:20 UTC, beplop commented on khamidullin_ar/main.py
> +            f_name = args[f_pos + 1]
Сначала проверяем, потом присваиваем ))

2023-03-05 17:31 UTC, beplop commented on khamidullin_ar/main.py
> +    if sub_strings:
tokens_to_substrings() функция возвращает либо bool, либо список строк. Тут я проверяю, что если все таки вернулся не bool, а список строк (что означает - функция выполнилась без ошибок), то я вывожу полученные подстроки в консоль, иначе выводится сообщение об ошибке.

2023-03-05 17:37 UTC, beplop commented on khamidullin_ar/main.py
> +        if sum([len(x) for x in buffer]) + len(token) + len(buffer) - 1 <= n:
Чтобы учитывать пробелы. Количество элементов в buffer равно количеству пробелов в подстроке. Вычитаем единицу, т.к. у последнего слова пробела нет.

2023-03-06 08:21 UTC, shadowk1337 approved these changes
Score: 6
- Base: +3
- Code Quality: +1
- Bonus 1: +1
- Bonus 2: +1

2023-03-08 08:26 UTC, xthebat commented on khamidullin_ar/input.txt
> +Scoreboard ���� ������: https://discord.com/channels/690164243685048457/806462228207239179/941307720076783686
Всё плохо :)

2023-03-08 08:26 UTC, merged