Task01 - Rozhkov A.
xthebat/iu4-2k23-python pull request #43
Opened 2023-03-01 17:34 UTC by Art-me-plz

Только первое задание без бонусов, пока еще не разобрался с функциями питона поэтому пишу как на си)

2023-03-05 04:27 UTC, shadowk1337 requested changes
Стоит пересмотреть алгоритм разделения строки и исправить недочеты
Программа на некоторых тестах уходит в бесконечный цикл

2023-03-05 04:27 UTC, shadowk1337 commented on rozhkov_aa/main.py
> +    if len(args) < 3:
Непонятно, что тут означает `3` - лучше вынести ее в константу

2023-03-05 04:27 UTC, shadowk1337 commented on rozhkov_aa/main.py
> +    for bottom in range(len(args)):
Тут лучше вместо колбасы `range(len(args))` использовать `enumerate`

2023-03-05 04:27 UTC, shadowk1337 commented on rozhkov_aa/main.py
> +        return 505
Это лучше проверять до чтения из файла

2023-03-05 04:27 UTC, shadowk1337 commented on rozhkov_aa/main.py
> +            pass
Это лучше вынести в другую функцию

2023-03-05 04:27 UTC, shadowk1337 commented on rozhkov_aa/main.py
> +    all_str: str = read_file(file_name)
Нейминг не очень

2023-03-05 04:27 UTC, shadowk1337 commented on rozhkov_aa/main.py
> +            if not all_str[top_border] == ' ' or all_str[top_border] == '\n':
Тут можно использовать функцию `isspace`

2023-03-08 09:27 UTC, Art-me-plz commented on rozhkov_aa/main.py
> +    for bottom in range(len(args)):
enumerate, как я понял, возвращает кортеж из индекса и значения, в данном же случае нужен только индекс, т.к. значения уже есть (ну или я как обычн6о не понял, как это правильно использовать)

2023-03-08 09:27 UTC, Art-me-plz commented on rozhkov_aa/main.py
> +        return 505
исправил

2023-03-08 09:28 UTC, Art-me-plz commented on rozhkov_aa/main.py
> +            if not all_str[top_border] == ' ' or all_str[top_border] == '\n':
тоже не понял пока как она работает, поэтому оставил как есть

2023-03-08 09:28 UTC, Art-me-plz commented on rozhkov_aa/main.py
> +    all_str: str = read_file(file_name)
исправил

2023-03-08 09:31 UTC, Art-me-plz commented
в общем поправил код, сейчас вроде бы должен пройти все тесты (но это не точно), не стал делать бонусы... Мне нужно посмотреть какой-нибудь видос типа "питон за 1 час" и мб тогда я что-то нормальное начну писать)

2023-03-09 05:10 UTC, shadowk1337 approved these changes
Score: 4
- Base: +3
- Code quality: +1

2023-04-09 11:08 UTC, merged