Saluev E.A. | Task 01
xthebat/iu4-2k23-python pull request #6
Opened 2023-02-25 10:48 UTC by evsxe

2023-02-25 11:15 UTC, evsxe commented on saluev_ea/main.py
> +    arguments.add_argument(
Я все еще верю, что сделаю хардкор

2023-02-26 10:27 UTC, xthebat requested changes
Score: -
- Base: -
- Code Quality: +1
- Bonus 1: +1
- Bonus 2: +1
- Argparse: +1

Код выглядит хорошо, за исключением:
- отрефакторить код и убрать эти ужасные вложенности. 
- убрать try-except - такое использование - это типичный anti-pattern и так делать не надо.

2023-02-26 10:27 UTC, xthebat commented on saluev_ea/main.py
> +    except Exception as e:
Это бессмыслено. Пользователь и так увидеть это исключение. Всё что делает этот try-except - это делает хуже. Вы лишаете себя бесценного stacktrace. И отладка после этого превратиться в кошмар. Обработка ошибок либо должна быть достаточно понятной и для пользователя, чтобы он понял, что он сделал не так при взаимодействии с Вашей программой, и для программиста, чтобы он понял что он написал не так. Либо её не должно быть и программист сможет получить доступ к стектрейсу.

2023-02-26 10:27 UTC, xthebat commented on saluev_ea/main.py
> +    if options.source and os.path.exists(options.source):  # Checking for the existence of a file
Минус вложенность:
```python
    if options.source and os.path.exists(options.source):  # Checking for the existence of a file
        print(f'File {options.source} not exist!', end='\n')
        return        
    file_handling(options)
```

2023-02-26 10:27 UTC, xthebat commented on saluev_ea/main.py
> +                print("File is empty.")
Тут можно выйти из функции

2023-02-26 10:27 UTC, xthebat commented on saluev_ea/main.py
> +                    print(f'\t{line.strip()}', end='\n')
И после этой строки

2023-02-26 10:27 UTC, xthebat commented on saluev_ea/main.py
> +            else:
И else тогда не нужен, минус вложенность

2023-02-26 10:27 UTC, xthebat commented on saluev_ea/main.py
> +                    if result:
Минус вложенность:
```python
if not result:
    continue
```

2023-02-26 10:27 UTC, xthebat commented on saluev_ea/main.py
> +                            if options.dir:
То же самое, читать код if и через 100 строк else к нему - невозможно. Обработали какой-то кейс и дальше делать нечего - выходим. Не нужно тянуться к этому else. 

Ну или разбиваем на функции

2023-02-26 10:27 UTC, xthebat commented on saluev_ea/main.py
> +        result.append(line)
см. ниже по поводу if-else

2023-02-26 10:27 UTC, xthebat commented on saluev_ea/main.py
> +    tag = False
Это всё действительно должно быть объявлено, выглядит как Pascal.

2023-02-26 10:27 UTC, xthebat commented on saluev_ea/main.py
> +def get_arguments():
За argparse - плюсую

2023-02-26 10:41 UTC, evsxe commented on saluev_ea/main.py
> +    except Exception as e:
Можно будет с вами пообщаться на эту тему? Хочу лучше понять ваше мнение 😊

2023-02-26 10:46 UTC, evsxe commented on saluev_ea/main.py
> +    if options.source and os.path.exists(options.source):  # Checking for the existence of a file
Насколько мне известно более грамотно использовать полностью конструкцию if else, использование простого if делает код менее качественным. Могу ошибаться, разумеется с:

2023-02-26 23:11 UTC, shadowk1337 commented on saluev_ea/main.py
> +    if options.source and os.path.exists(options.source):  # Checking for the existence of a file
Ээээм, а что некачественного в неиспользовании добавочного `else`? Согласись гораздо красивее так:
```python
if some_condition:
    amogus = "amogus"
    return

some
logic
here
```
Чем так:
```python
if some_condition:
    amogus = "amogus"
    return
else:
    some
    logic
    here
```
Мы, во-первых, избавляемся от лишних табуляций, во-вторых, чисто визуально видно, что в `if` мы выходим из функции. Везде, где можно использую эту конструкцию и нигде о ее некачественном использовании не слышал...

2023-02-27 18:35 UTC, evsxe commented
@xthebat Исправил замечания и добавил функционал hardcore

2023-03-08 09:35 UTC, xthebat reviewed
Score: 8
Base: +3
CQ: +1
Bonus 1: +1
Bonus 2: +1
Hardcore: +2

Но коменты желательно поправить, особенно грустна склейка строк

2023-03-08 09:35 UTC, xthebat commented on saluev_ea/main.py
> +        elif options.num in [0, 1]:
Ну тут elif же не нужен, если условие 106-й строки выполнилось - то уже выйдем из функции, зачем опять вложенность?

2023-03-08 09:35 UTC, xthebat commented on saluev_ea/main.py
> +        for line in source_file:
А тут уже нету else/elif :) +1

2023-03-08 09:35 UTC, xthebat commented on saluev_ea/main.py
> +            for substring in line_separator(line, options):
Выглядит, что можно заюзать `enumerate(..., start=1)`

2023-03-08 09:35 UTC, xthebat commented on saluev_ea/main.py
> +                        print(f'Path {options.dir} does not exist\n')
Это надо проверить раньше и завершить выполнение программы - иначе программа на каждый кусок выдаст это сообщение, что не имеет смысла. И соответственно после этого все эти if-else тут пропадут. Да и вообще валидировать аргументы лучше до основной логики программы, а не замешивать это вместе.

В 135-й строке:
```python
if options.dir is not None and not os.path.exists(options.dir):
     exit(f'Path {options.dir} does not exist\n')
```

2023-03-08 09:35 UTC, xthebat commented on saluev_ea/main.py
> +            elif word.find(':') != -1:
`elif` не нужен, лучше `if`

2023-03-08 09:35 UTC, xthebat commented on saluev_ea/main.py
> +            substring += f'{word} '
Склейка строк в цикле - это плохо, строки не изменяемый тип данных. Это ведет к перекопированию всей предыдущей строки при добавлении кусочка. Это относится и к C++, C#, Java/JVM

2023-03-08 09:35 UTC, xthebat commented on saluev_ea/main.py
> +        raise CantEvaluate(options.row) from error
+1

2023-03-08 09:45 UTC, xthebat commented on saluev_ea/main.py
> +    if options.source and os.path.exists(options.source):  # Checking for the existence of a file
Вот пример: https://github.com/kollegekidd/iu4-2k23-python/blob/59e7a8b07853481fa322da1c1d579b60e533ec25/efremenkov_ia/main.py#L31

Читается просто идеально и всё сразу понятно. Не прошло условие - вышли, не прошло следующее - вышли. И т.д. "более грамотно использовать полностью конструкцию if else" - звучит как мантра без аргументации :|

2023-03-12 19:13 UTC, merged