Task01 Ryzhov Feodor
xthebat/iu4-2k23-python pull request #7
Opened 2023-02-25 18:41 UTC by felloryz

Реализовал task01 с учетом Bonus 1 и Bonus 2. 

Логика работы скрипта:
1. Парсим аргументы
2. Записываем содержимое файла в строку и работаем с ней
3. Создаем список индексов тегов — тег начинается с '@' заканчивается ':' — значит, делить по этим индексам нельзя
4. Далее определяем начальную и конечную позиции первой подстроки (конец = начало + -n)
5. Если конец подстроки попал в середину слова или в запретный список индексов, двигаем конечную позицию подстроки влево до первого пробела или \n
6. Теперь конец первой подстроки становиться началом следующей подстроки и т.д.
7. Так мы определяем начало и конец каждой подстроки
8. Печатем в консоль или в файл

2023-02-26 23:47 UTC, shadowk1337 requested changes
Норм, исправь недочеты и будет класс

2023-02-26 23:47 UTC, shadowk1337 commented on ryzhov_fs/task01/task01.iml
> +</module>
Этот файл лучше удалить или в `.gitignore`

2023-02-26 23:47 UTC, shadowk1337 commented on ryzhov_fs/task01/main.py
> +    if (f_index + 1) <= (len(argv) - 1):
Можно просто 
```python
if f_index + 1 < len(argv):
```

2023-02-26 23:47 UTC, shadowk1337 commented on ryzhov_fs/task01/main.py
> +        return -1
Давай уберем с этой функции ответственность на вывод чего-то в консоль, лучше вынеси вывод трейса об ошибке в другую функцию и с принтами ниже то же самое

2023-02-26 23:47 UTC, shadowk1337 commented on ryzhov_fs/task01/main.py
> +        if (n_index + 1) <= (len(argv) - 1):
```python
if n_index + 1 < len(argv):
```

2023-02-26 23:47 UTC, shadowk1337 commented on ryzhov_fs/task01/main.py
> +            if argv[n_index + 1] not in args_set and argv[n_index + 1].isdigit():
Попробуй вынести `argv[n_index + 1]` в переменную, а то довольно много здесь ее использований

2023-02-26 23:47 UTC, shadowk1337 commented on ryzhov_fs/task01/main.py
> +        args_dict["-l"] = "True"
Тут можно прямо `True` присвоить

2023-02-26 23:47 UTC, shadowk1337 commented on ryzhov_fs/task01/main.py
> +                 "-d": "False"}
В значения словаря можно разные типы пихать и записать это так:
```python
args_dict = {"-f": "",
             "-n": 200,
             "-l": False,
             "-d": False}
```

2023-02-26 23:47 UTC, shadowk1337 commented on ryzhov_fs/task01/main.py
> +        if (d_index + 1) <= (len(argv) - 1):
Писал выше

2023-02-26 23:47 UTC, shadowk1337 commented on ryzhov_fs/task01/main.py
> +    # print(tag_exception_indexes)
👍

2023-02-26 23:47 UTC, shadowk1337 commented on ryzhov_fs/task01/main.py
> +    # print(tag_exception_indexes)
Такие коменты в топку, их в коде быть не должно. В будущем они тебе никак не помогут

2023-02-26 23:47 UTC, shadowk1337 commented on ryzhov_fs/task01/main.py
> +            sep_space = ''
```python
sep_space = ' ' if not line_sep_flag else ''
```

2023-02-26 23:47 UTC, shadowk1337 commented on ryzhov_fs/task01/main.py
> +    if output_file_path == False:
```python
if not output_file_path:
```

2023-02-26 23:47 UTC, shadowk1337 commented on ryzhov_fs/task01/main.py
> +            elif high_sep_index in tag_exception_indexes and line_sep_flag != True:
```python
elif high_sep_index in tag_exception_indexes and not line_sep_flag:
```

2023-02-26 23:47 UTC, shadowk1337 commented on ryzhov_fs/task01/main.py
> +            print(f'Substring length: {len(file_str[sep_indexes[it]:sep_indexes[it + 1]])}')
Ок, мб я сейчас ночью что-то не догоняю, а зачем писать
```python
len(file_str[sep_indexes[it]:sep_indexes[it + 1]])
```
а не
```python
sep_indexes[it + 1] - sep_indexes[it]
```

2023-02-26 23:47 UTC, shadowk1337 commented on ryzhov_fs/task01/main.py
> +            f = open(file_name, 'w', encoding="UTF-8")
Вместо `open()` используй конструкцию
```python
with open() as f:
```
и тебе не придется самому следить за корректным закрытием файла

2023-02-26 23:47 UTC, shadowk1337 commented on ryzhov_fs/task01/main.py
> +            f.write(f'Substring length: {len(file_str[sep_indexes[it]:sep_indexes[it + 1]])}\n')
Написал выше

2023-02-26 23:47 UTC, shadowk1337 commented on ryzhov_fs/task01/main.py
> +            # f.write(f'\t{file_str[sep_indexes[it]:sep_indexes[it + 1]]}')
Сжечь

2023-02-26 23:47 UTC, shadowk1337 commented on ryzhov_fs/task01/main.py
> +        return 0
При ошибке в программе мы возвращаем 0?

2023-02-26 23:47 UTC, shadowk1337 commented on ryzhov_fs/task01/main.py
> +        max_substring_len = int(args_dict["-n"])
Таких кастов можно избежать, если юзать словарь с нестринговыми значениями, как я выше показал

2023-02-26 23:47 UTC, shadowk1337 commented on ryzhov_fs/task01/main.py
> +            output_file_path = False
Ну даааа

2023-02-26 23:47 UTC, shadowk1337 commented on ryzhov_fs/task01/main.py
> +    f.close()
Выше про это написал

2023-02-27 14:07 UTC, felloryz commented on ryzhov_fs/task01/main.py
> +        return -1
То есть заменить print() на вызов другой функции, которая и будет выводить сообщение об ошибке? Или делать return целочисленной переменной, за которой будет закреплено определенное сообщение об ошибке (типа 1 — «нет параметра -f», 2 — «нет параметра -d» и так далее)?

2023-02-27 16:20 UTC, shadowk1337 commented on ryzhov_fs/task01/main.py
> +        return -1
Попробуй при ошибке возврщать только `-1` из функции. А в месте, где эту функцию вызываешь чекать , что из нее пришло и если пришло `-1`, то выводить строку типа:
```python
program.py Usage:
    -h     Print help
    -f      Write to file
```

2023-02-28 07:57 UTC, felloryz commented
Исправил все замечания

2023-03-06 11:08 UTC, shadowk1337 approved these changes
Score: 6
- Base: +3
- Code Quality: +1
- Bonus 1: +1
- Bonus 2: +1

2023-03-08 09:22 UTC, merged