Task01 Alimova Polina
xthebat/iu4-2k23-python pull request #8
Opened 2023-02-25 19:27 UTC by PolinaAlimova11

2023-02-26 10:41 UTC, xthebat requested changes

2023-02-26 10:41 UTC, xthebat commented on alimova_pd/dz_01.py
> +        return 'ValueError'
Уф, так делать не надо. 
1. Писать сообщение об ошибке необходимо выше.
2. Возвращать в случае, если не нашлось нужно `None` и проверять на него.

2023-02-26 10:41 UTC, xthebat commented on alimova_pd/dz_01.py
> +    return args[index_f + 1]
А тут проверки нету :) Что если, я укажу -f последним аргументом

2023-02-26 10:41 UTC, xthebat commented on alimova_pd/dz_01.py
> +def symbol_file(args: list[str]) -> int:
Аналогично, если функция не может вернуть значение - возвращаем None

2023-02-26 10:41 UTC, xthebat commented on alimova_pd/dz_01.py
> +            spisok.append(in_str[last_final:probel])
spisok ... не надо ... транслита, пожалуйста.

2023-02-26 10:41 UTC, xthebat commented on alimova_pd/dz_01.py
> +        if (i - probel) < limit <= counter:
Транслит использовать нельзя

2023-02-26 10:41 UTC, xthebat commented on alimova_pd/dz_01.py
> +            probel = i
Тем более, что это индекс пробела, то есть space_index

2023-02-26 10:41 UTC, xthebat commented on alimova_pd/dz_01.py
> +            flag = True
Так можно убрать этот flag и внутри if-а напечатать сообщение и выйти с пустым списком, а лучше с None

2023-02-26 10:41 UTC, xthebat commented on alimova_pd/dz_01.py
> +def check_spisok(spisok: list[str]):
Пачему транслит, за что?!

2023-02-26 10:41 UTC, xthebat commented on alimova_pd/dz_01.py
> +        name_file = direct + '\\substring_' + str(i) + '.txt'
Не надо клеить строки, используйте интерполяцию, я про неё рассказывал.

2023-02-26 10:41 UTC, xthebat commented on alimova_pd/dz_01.py
> +        name_file = direct + '\\substring_' + str(i) + '.txt'
Для сборки пути используйте os.path.join

2023-02-26 10:41 UTC, xthebat commented on alimova_pd/dz_01.py
> +        print(spisok[i])
Дополнительную пустую строку можно распечатать с помощью print(...., end="\n\n")

2023-02-26 10:41 UTC, xthebat commented on alimova_pd/dz_01.py
> +    for i in range(len(spisok)):
Итерироваться с индексом можно с помощью enumerate

2023-02-26 10:41 UTC, xthebat commented on alimova_pd/dz_01.py
> +    probel = 0  # индекс последнего пробела
Вместо комментариев лучше использовать понятные имена, тогда комментарии будут не нужны

2023-02-26 10:41 UTC, xthebat commented on alimova_pd/dz_01.py
> +    flag = False
Тоже самое, что за флаг? России? Украины? США? Германии? Для чего? Задайте имя из которого будет сразу понятно, что нашли "собаку" в строки и т.п.

2023-02-26 10:41 UTC, xthebat commented on alimova_pd/dz_01.py
> +        str_1 = file.read()
Можно одной строкой `return file.read()`

2023-02-27 14:03 UTC, PolinaAlimova11 commented on alimova_pd/dz_01.py
> +        return 'ValueError'
Простите, не очень понимаю 1 замечание. Писать не в данной функции? Писать до проверки?

2023-03-06 11:43 UTC, shadowk1337 approved these changes
Score: 6
- Base: +3
- Code Quality: +1
- Bonus 1: +1
- Bonus 2: +1

2023-03-08 09:22 UTC, merged